#@data/values

#@overlay/match-child-defaults missing_ok=True
---
tap:
  version: "1.2.0-build.10"
  namespace: tap-install
  catalogs: []

  registry:
    host: tapdemoregistry.azurecr.io
    repositories:
      buildService: repo/build-service
      ootbSupplyChain: repo/supply-chain

  domains:
    main: tap.tanzu4u.net
    tapGui: tap-gui.tap.tanzu4u.net
